# main.yml
# 一个 workflow，名字为Github Action Example
name: Github Action Example

# 触发 workflow 的事件
on:
  push:
    # 分支随意
    branches:
      - main

# 一个workflow由执行的一项或多项job
jobs:
    # 一个job任务，任务名为build
    build:
        # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
        runs-on: ubuntu-latest
        # steps是每个Job的运行步骤，可以包含一个或多个步骤
        steps:
            # action命令，切换分支获取源码
            - name: Checkout
                # 使用action库  actions/checkout获取源码
                uses: actions/checkout@main
            # action命令，安装Node16
            - name: use Node.js 16
                # 使用action库  actions/setup-node安装node
                uses: actions/setup-node@v1
                with:
                    node-version: 16
            # action命令，install && test
            - name: npm install and build
                # 运行的命令或者 action
                run: |
                    npm install
                    npm run build
                # 环境变量
                env:
                    CI: true
            # Deploy
            - name: Deploy
              uses:JamesIves/github-pages-deploy-action@releases/v3
              with:
                ACCESS_TOKEN: ${{ secrets.TEST_ACTION }}
                BRANCH: gh-pages
                FOLDER: build
